// <auto-generated />
using System;
using ComprovantesApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComprovantesApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComprovantesApp.Models.Comprovante", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DataEmissao")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DataIntegracao")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DataValidacao")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DataVencimento")
                    .HasColumnType("datetime2");

                b.Property<string>("Descricao")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("FornecedorId")
                    .HasColumnType("int");

                b.Property<string>("NumeroDocumento")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("ObservacaoInconsistencia")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<decimal>("Valor")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("FornecedorId", "NumeroDocumento")
                    .IsUnique();

                b.ToTable("Comprovantes");
            });

            modelBuilder.Entity("ComprovantesApp.Models.Fornecedor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Ativo")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Cnpj")
                    .IsRequired()
                    .HasMaxLength(18)
                    .HasColumnType("nvarchar(18)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<int>("TipoFornecedor")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Fornecedores");
            });

            modelBuilder.Entity("ComprovantesApp.Models.HistoricoComprovante", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Acao")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("ComprovanteId")
                    .HasColumnType("int");

                b.Property<DateTime>("DataHora")
                    .HasColumnType("datetime2");

                b.Property<string>("Descricao")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.HasKey("Id");

                b.HasIndex("ComprovanteId");

                b.ToTable("Historicos");
            });

            modelBuilder.Entity("ComprovantesApp.Models.Comprovante", b =>
            {
                b.HasOne("ComprovantesApp.Models.Fornecedor", "Fornecedor")
                    .WithMany("Comprovantes")
                    .HasForeignKey("FornecedorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Fornecedor");
            });

            modelBuilder.Entity("ComprovantesApp.Models.HistoricoComprovante", b =>
            {
                b.HasOne("ComprovantesApp.Models.Comprovante", "Comprovante")
                    .WithMany("Historicos")
                    .HasForeignKey("ComprovanteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Comprovante");
            });

            modelBuilder.Entity("ComprovantesApp.Models.Comprovante", b =>
            {
                b.Navigation("Historicos");
            });

            modelBuilder.Entity("ComprovantesApp.Models.Fornecedor", b =>
            {
                b.Navigation("Comprovantes");
            });
#pragma warning restore 612, 618
        }
    }
}
